name: Pre Commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install pre-commit with pipx
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files
        continue-on-error: true # Continue even if pre-commit fails

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5

  pre-commit-changed-files:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install pre-commit with pipx
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install pre-commit
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        # with:
        #   since_last_remote_commit: true

      - name: Run pre-commit
        run: |
          pre-commit run --files ${{ steps.changed-files.outputs.all_changed_files }}
        continue-on-error: true # Continue even if pre-commit fails

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
